#!/usr/bin/env bash

set -euo pipefail

script_directory="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

if [[ $# -gt 1 ]]; then
    printf 'Usage: %s [PrusaSlicer-config-directory]\n' "$0" >&2
    exit 2
fi

if [[ $# -eq 1 ]]; then
    config_directory="${1/#\~/$HOME}"
elif [[ -d "$HOME/.var/app/com.prusa3d.PrusaSlicer/config/PrusaSlicer" ]]; then
    config_directory="$HOME/.var/app/com.prusa3d.PrusaSlicer/config/PrusaSlicer"
elif [[ -d "$HOME/.config/PrusaSlicer" ]]; then
    config_directory="$HOME/.config/PrusaSlicer"
else
    printf '%s\n' 'Could not find a PrusaSlicer configuration directory.' >&2
    printf '%s\n' 'Start PrusaSlicer once, close it, and rerun this script.' >&2
    printf 'Or specify the directory: %s /path/to/PrusaSlicer\n' "$0" >&2
    exit 1
fi

if pgrep -x prusa-slicer >/dev/null 2>&1 || pgrep -x PrusaSlicer >/dev/null 2>&1; then
    printf '%s\n' 'PrusaSlicer appears to be running.' >&2
    printf '%s\n' 'Close it before installing presets so it does not overwrite them.' >&2
    exit 1
fi

if [[ ! -f "$config_directory/PrusaSlicer.ini" ]]; then
    printf 'No PrusaSlicer.ini found in: %s\n' "$config_directory" >&2
    printf '%s\n' 'Run the Configuration Wizard once before installing this bundle.' >&2
    exit 1
fi

required_parent='Original Prusa MK4S MMU3 0.4 nozzle'
if ! grep -Fq 'model:MK4SMMU3' "$config_directory/PrusaSlicer.ini"; then
    printf 'Required bundled parent preset is not enabled: %s\n' "$required_parent" >&2
    printf '%s\n' 'Enable MK4S MMU3 0.4 and 0.6 in the Configuration Wizard first.' >&2
    exit 1
fi

timestamp="$(date -u +%Y%m%dT%H%M%SZ)"
backup_directory="$config_directory/preset-backup-before-install-$timestamp"
installed_count=0
updated_count=0
unchanged_count=0

# Register the new vendor variant in the Configuration Wizard's enabled list.
config_work_file="$(mktemp)"
selected_printer="$(sed -n 's/^printer = //p' "$config_directory/PrusaSlicer.ini")"
awk -v link_physical="$([[ "$selected_printer" == 'Original Prusa MK4S MMU3 0.25 nozzle' ]] && printf 1 || printf 0)" '
    /^model:MK4SMMU3[[:space:]]*=/ {
        if ($0 !~ /0\.25/) {
            sub(/=[[:space:]]*/, "= 0.25;")
            changed = 1
        }
    }
    link_physical && /^physical_printer[[:space:]]*=[[:space:]]*$/ {
        print "physical_printer = Prusa MK4S * Original Prusa MK4S MMU3 0.25 nozzle"
        next
    }
    { print }
' "$config_directory/PrusaSlicer.ini" > "$config_work_file"
if cmp -s "$config_work_file" "$config_directory/PrusaSlicer.ini"; then
    rm -f "$config_work_file"
    printf '%s\n' 'MK4S MMU3 0.25 selection is already current in PrusaSlicer.ini'
    ((unchanged_count += 1))
else
    mkdir -p "$backup_directory"
    cp -p "$config_directory/PrusaSlicer.ini" "$backup_directory/"
    cp -p "$config_work_file" "$config_directory/PrusaSlicer.ini"
    rm -f "$config_work_file"
    printf '%s\n' 'Enabled and linked MK4S MMU3 0.25 in PrusaSlicer.ini'
    ((updated_count += 1))
fi

install_preset() {
    local preset_type="$1"
    local preset_name="$2"
    local source="$script_directory/$preset_type/$preset_name"
    local destination_directory="$config_directory/$preset_type"
    local destination="$destination_directory/$preset_name"

    if [[ ! -f "$source" ]]; then
        printf 'Backup bundle is incomplete; missing: %s\n' "$source" >&2
        exit 1
    fi

    mkdir -p "$destination_directory"
    if [[ -f "$destination" ]]; then
        if cmp -s "$source" "$destination"; then
            printf 'Already current %s/%s\n' "$preset_type" "$preset_name"
            ((unchanged_count += 1))
            return
        fi

        mkdir -p "$backup_directory/$preset_type"
        cp -p "$destination" "$backup_directory/$preset_type/"
        cp -p "$source" "$destination"
        printf 'Updated %s/%s\n' "$preset_type" "$preset_name"
        ((updated_count += 1))
        return
    fi

    cp -p "$source" "$destination"
    printf 'Installed %s/%s\n' "$preset_type" "$preset_name"
    ((installed_count += 1))
}

install_preset physical_printer 'Prusa MK2.5S.ini'
install_preset physical_printer 'Prusa MK4S.ini'
install_preset filament 'PLA Low Temp.ini'

# Prusa does not publish 0.25 mm MMU3 filament variants. Mirror each enabled
# standard MK4S filament as a small inheriting preset pinned to our printer.
while IFS= read -r source_filament; do
    copied_filament="$source_filament MMU3 0.25"
    preset_name="$copied_filament.ini"
    destination_directory="$config_directory/filament"
    destination="$destination_directory/$preset_name"
    generated_marker='# Generated by prusa-config-presets; source: MK4S 0.25 filament'
    desired_content="${generated_marker}
compatible_printers =
compatible_printers_condition = printer_model==\"MK4SMMU3\" and nozzle_diameter[0]==0.25
filament_settings_id = ${copied_filament}
inherits = ${source_filament}"

    mkdir -p "$destination_directory"
    if [[ -f "$destination" ]]; then
        if [[ "$(cat "$destination")" == "$desired_content" ]]; then
            printf 'Already current filament/%s\n' "$preset_name"
            ((unchanged_count += 1))
            continue
        fi
        if ! grep -Fqx "$generated_marker" "$destination"; then
            printf 'Refusing to replace non-generated filament preset: %s\n' "$destination" >&2
            exit 1
        fi
        mkdir -p "$backup_directory/filament"
        cp -p "$destination" "$backup_directory/filament/"
        printf 'Updated filament/%s\n' "$preset_name"
        ((updated_count += 1))
    else
        printf 'Installed filament/%s\n' "$preset_name"
        ((installed_count += 1))
    fi
    printf '%s\n' "$desired_content" > "$destination"
done < <(awk '
    /^\[filaments\]$/ { in_filaments = 1; next }
    in_filaments && /^\[/ { exit }
    in_filaments && / @MK4S[[:space:]]*=[[:space:]]*1[[:space:]]*$/ {
        sub(/[[:space:]]*=[[:space:]]*1[[:space:]]*$/, "")
        print
    }
' "$config_directory/PrusaSlicer.ini")

vendor_preset_file="$config_directory/vendor/PrusaResearch.ini"
if [[ ! -f "$vendor_preset_file" ]]; then
    printf 'Required bundled preset file is missing: %s\n' "$vendor_preset_file" >&2
    exit 1
fi

vendor_work_file="$(mktemp)"
cp -p "$vendor_preset_file" "$vendor_work_file"

disable_binary_gcode_for_vendor_preset() {
    local preset_name="$1"
    local next_work_file
    next_work_file="$(mktemp)"

    awk -v target="[printer:$preset_name]" '
        BEGIN { in_target = 0; found_target = 0; wrote_option = 0 }
        /^\[/ {
            if (in_target && !wrote_option) {
                print "binary_gcode = 0"
                wrote_option = 1
            }
            in_target = ($0 == target)
            if (in_target) found_target = 1
        }
        in_target && /^binary_gcode[[:space:]]*=/ {
            if (!wrote_option) print "binary_gcode = 0"
            wrote_option = 1
            next
        }
        { print }
        END {
            if (in_target && !wrote_option) print "binary_gcode = 0"
            if (!found_target) exit 3
        }
    ' "$vendor_work_file" > "$next_work_file" || {
        rm -f "$vendor_work_file" "$next_work_file"
        printf 'Bundled printer preset was not found: %s\n' "$preset_name" >&2
        exit 1
    }

    mv "$next_work_file" "$vendor_work_file"
}

disable_binary_gcode_for_vendor_preset 'Original Prusa i3 MK2.5S'
disable_binary_gcode_for_vendor_preset 'Original Prusa MK4S 0.25 nozzle'
disable_binary_gcode_for_vendor_preset 'Original Prusa MK4S 0.4 nozzle'
disable_binary_gcode_for_vendor_preset 'Original Prusa MK4S 0.6 nozzle'
disable_binary_gcode_for_vendor_preset 'Original Prusa MK4S MMU3 0.4 nozzle'
disable_binary_gcode_for_vendor_preset 'Original Prusa MK4S MMU3 0.6 nozzle'

# The standard MK4S 0.25 parents exclude all single-extruder multimaterial
# printers. Permit only our otherwise unsupported MK4S MMU3 0.25 combination.
next_work_file="$(mktemp)"
awk '
    /^\[(print|filament):/ { in_profile = 1 }
    /^\[/ && $0 !~ /^\[(print|filament):/ { in_profile = 0 }
    in_profile && /^compatible_printers_condition[[:space:]]*=/ &&
        index($0, "! single_extruder_multi_material") &&
        !index($0, "printer_model==\"MK4SMMU3\" and nozzle_diameter[0]==0.25") {
        sub(/! single_extruder_multi_material/,
            "(! single_extruder_multi_material or (printer_model==\"MK4SMMU3\" and nozzle_diameter[0]==0.25))")
    }
    { print }
' "$vendor_work_file" > "$next_work_file"
mv "$next_work_file" "$vendor_work_file"

next_work_file="$(mktemp)"
awk '
    /^\[printer_model:MK4SMMU3\]$/ { in_model = 1 }
    in_model && /^variants[[:space:]]*=/ {
        if ($0 !~ /0\.25/)
            sub(/^variants[[:space:]]*=[[:space:]]*/, "variants = 0.25; ")
        in_model = 0
    }
    in_model && /^\[/ && $0 != "[printer_model:MK4SMMU3]" { exit 3 }
    { print }
' "$vendor_work_file" > "$next_work_file" || {
    rm -f "$vendor_work_file" "$next_work_file"
    printf '%s\n' 'Bundled MK4SMMU3 printer model or variants declaration was not found.' >&2
    exit 1
}
mv "$next_work_file" "$vendor_work_file"

if ! grep -Fqx '[printer:Original Prusa MK4S MMU3 0.25 nozzle]' "$vendor_work_file"; then
    printf '%s\n' '' \
        '; Added by prusa-config-presets for the unsupported MMU3 0.25 combination.' \
        '[printer:Original Prusa MK4S MMU3 0.25 nozzle]' \
        'inherits = Original Prusa MK4S MMU3 0.4 nozzle' 'printer_variant = 0.25' \
        'nozzle_diameter = 0.25,0.25,0.25,0.25,0.25' 'retract_length = 0.8,0.8,0.8,0.8,0.8' \
        'retract_lift = 0.15,0.15,0.15,0.15,0.15' 'max_layer_height = 0.15,0.15,0.15,0.15,0.15' \
        'min_layer_height = 0.05,0.05,0.05,0.05,0.05' \
        'default_print_profile = 0.15mm SPEED @MK4S 0.25' \
        'default_filament_profile = "Prusament PLA @MK4S"' 'binary_gcode = 0' >> "$vendor_work_file"
fi

if cmp -s "$vendor_work_file" "$vendor_preset_file"; then
    rm -f "$vendor_work_file"
    printf '%s\n' 'Bundled Prusa preset overrides are already current.'
    ((unchanged_count += 1))
else
    mkdir -p "$backup_directory/vendor"
    cp -p "$vendor_preset_file" "$backup_directory/vendor/"
    cp -p "$vendor_work_file" "$vendor_preset_file"
    rm -f "$vendor_work_file"
    printf '%s\n' 'Updated bundled Prusa presets for binary G-code and MMU3 0.25 compatibility.'
    ((updated_count += 1))
fi

shadow_printer="$config_directory/printer/Original Prusa MK4S MMU3 0.25 nozzle.ini"
if [[ -f "$shadow_printer" ]]; then
    mkdir -p "$backup_directory/printer"
    cp -p "$shadow_printer" "$backup_directory/printer/"
    rm -f "$shadow_printer"
    printf '%s\n' 'Removed shadowing user printer/Original Prusa MK4S MMU3 0.25 nozzle.ini'
    ((updated_count += 1))
fi

# Remove superseded override files created by an earlier version of this bundle.
# Those files are identified by the alias metadata that the current clean-named
# presets no longer use.
for obsolete_preset in "$config_directory/printer/"*.ini; do
    [[ -f "$obsolete_preset" ]] || continue
    if grep -Fq 'alias = Original Prusa' "$obsolete_preset" && \
        grep -Fq 'binary_gcode = 0' "$obsolete_preset"; then
        mkdir -p "$backup_directory/printer"
        cp -p "$obsolete_preset" "$backup_directory/printer/"
        rm -f "$obsolete_preset"
        printf 'Removed superseded printer/%s\n' "$(basename "$obsolete_preset")"
        ((updated_count += 1))
    elif grep -Fq '# Match the bundled preset name while overriding its binary G-code capability.' "$obsolete_preset"; then
        mkdir -p "$backup_directory/printer"
        cp -p "$obsolete_preset" "$backup_directory/printer/"
        rm -f "$obsolete_preset"
        printf 'Removed ineffective duplicate printer/%s\n' "$(basename "$obsolete_preset")"
        ((updated_count += 1))
    fi
done

printf '\nPreset synchronization complete: %d installed, %d updated, %d already current.\n' \
    "$installed_count" "$updated_count" "$unchanged_count"
printf 'PrusaSlicer configuration directory:\n  %s\n' "$config_directory"
if ((updated_count > 0)); then
    printf 'Replaced files were backed up in:\n  %s\n' "$backup_directory"
fi
printf '%s\n' 'Start PrusaSlicer and verify the physical-printer selector.'
