# Cleaned for PrusaSlicer 2.9.6 on 2026-07-14
host_type = prusalink
preset_name = Original Prusa i3 MK2.5S;Original Prusa i3 MK2.5S
preset_names = "Original Prusa i3 MK2.5S";"Original Prusa i3 MK2.5S"
print_host = oldprinter.lan
printer_technology = FFF
printhost_apikey = OWm1HWRdyoqjVsWX-hY2Q-QSheuI6DMIASf5z2EAPC0
printhost_authorization_type = key
printhost_cafile = 
printhost_password = 
printhost_port = 
printhost_ssl_ignore_revoke = 0
printhost_user = 
