# Cleaned for PrusaSlicer 2.9.6 on 2026-07-14
host_type = prusalink
preset_name = Original Prusa MK4S 0.4 nozzle;Original Prusa MK4S 0.4 nozzle
preset_names = "Original Prusa MK4S 0.25 nozzle";"Original Prusa MK4S 0.4 nozzle";"Original Prusa MK4S 0.6 nozzle";"Original Prusa MK4S MMU3 0.25 nozzle";"Original Prusa MK4S MMU3 0.4 nozzle";"Original Prusa MK4S MMU3 0.6 nozzle"
print_host = newprinter.lan
printer_technology = FFF
printhost_apikey = wsrxhlZ1v9RnXoL93WIomyvY2dhD_v5o-u02YjA1xDE
printhost_authorization_type = key
printhost_cafile = 
printhost_password = 
printhost_port = 
printhost_ssl_ignore_revoke = 0
printhost_user = 
